version: '3.4'

services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pwd
      POSTGRES_DB: test_db

  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./test:/opt/pg-evolve/evolutions
    command: ["sh", "-c", "until psql -c '\\q' 2> /dev/null; do sleep 1; done && pg-evolve"]
    environment:
      PGHOST: db
      PGUSER: test_user
      PGPASSWORD: test_pwd
      PGDATABASE: test_db
