version: '3.4'

x-psql-env:
  &psql-env
  PGHOST: db
  PGUSER: test_user
  PGPASSWORD: test_pwd
  PGDATABASE: test_db

services:
  db:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pwd
      POSTGRES_DB: test_db
    logging:
      driver: none

  test:
    build: test/
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/opt/pg-evolve
    working_dir: /opt/pg-evolve
    command: ["./test/test.sh"]
    environment:
      << : *psql-env

  # app:
  #   build: .
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./samples:/opt/pg-evolve/evolutions
  #   command: ["sh", "-c", "until psql -c '\\q' 2> /dev/null; do sleep 1; done && pg-evolve && psql -c 'SELECT * FROM person;' && psql -c 'SELECT * FROM pg_evolve_evolutions'"]
  #   environment:
  #     << : *psql-env
